version: '3.8'

services:
  flask-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - PYTHONUNBUFFERED=1
    env_file: 
      - .env

  streamlit-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - flask-app